import type { RxVersion } from "./types";

// 演示数据：首次进入（localStorage 为空）时写入，之后只由用户提交追加
export function seedVersions(): RxVersion[] {
  return [
    {
      id: "seed-032-v1",
      patientId: "Patient-032",
      patientName: "李小童",
      category: "儿童近视",
      version: 1,
      kind: "initial",
      createdAt: "2026-06-10T09:20:00.000Z",
      right: { sphere: -2.0, cylinder: -0.5, axis: 180 },
      left: { sphere: -1.75, cylinder: -0.25, axis: 5 },
      vision: {
        OD: { unaided: "0.3", corrected: "1.0" },
        OS: { unaided: "0.4", corrected: "1.0" },
      },
      pd: 58,
      changes: [],
      note: "首次配镜，嘱咐增加户外活动。",
    },
    {
      id: "seed-032-v2",
      patientId: "Patient-032",
      patientName: "李小童",
      category: "儿童近视",
      version: 2,
      kind: "review",
      createdAt: "2026-08-12T10:05:00.000Z",
      right: { sphere: -2.75, cylinder: -0.5, axis: 180 },
      left: { sphere: -1.75, cylinder: -0.25, axis: 5 },
      vision: {
        OD: { unaided: "0.2", corrected: "1.0" },
        OS: { unaided: "0.4", corrected: "1.0" },
      },
      pd: 58,
      changes: [
        {
          eye: "OD",
          field: "sphere",
          oldValue: -2.0,
          newValue: -2.75,
          delta: -0.75,
          reason: "暑假用眼负荷增加，眼轴增长，复验近视进展 0.75D，矫正视力仍达 1.0。",
        },
      ],
      note: "建议低浓度阿托品联合角膜塑形镜评估，三个月后复查。",
    },
    {
      id: "seed-081-v1",
      patientId: "Patient-081",
      patientName: "王渐进",
      category: "渐进片",
      version: 1,
      kind: "initial",
      createdAt: "2026-09-05T14:40:00.000Z",
      right: { sphere: 0.5, cylinder: -0.75, axis: 90 },
      left: { sphere: 0.75, cylinder: -0.5, axis: 85 },
      vision: {
        OD: { unaided: "0.6", corrected: "0.9" },
        OS: { unaided: "0.6", corrected: "0.9" },
      },
      pd: 62,
      changes: [],
      note: "ADD +1.50，瞳高待确认，试戴适应后回店调整。",
    },
    {
      id: "seed-144-v1",
      patientId: "Patient-144",
      patientName: "张散光",
      category: "散光",
      version: 1,
      kind: "initial",
      createdAt: "2026-03-02T11:00:00.000Z",
      right: { sphere: -1.25, cylinder: -0.75, axis: 10 },
      left: { sphere: -1.0, cylinder: -0.5, axis: 170 },
      vision: {
        OD: { unaided: "0.5", corrected: "1.0" },
        OS: { unaided: "0.5", corrected: "1.0" },
      },
      pd: 60,
      changes: [],
      note: "初次矫正散光，适应期两周。",
    },
    {
      id: "seed-144-v2",
      patientId: "Patient-144",
      patientName: "张散光",
      category: "散光",
      version: 2,
      kind: "review",
      createdAt: "2026-05-20T15:25:00.000Z",
      right: { sphere: -1.25, cylinder: -1.5, axis: 10 },
      left: { sphere: -1.0, cylinder: -0.5, axis: 170 },
      vision: {
        OD: { unaided: "0.4", corrected: "1.0" },
        OS: { unaided: "0.5", corrected: "1.0" },
      },
      pd: 60,
      changes: [
        {
          eye: "OD",
          field: "cylinder",
          oldValue: -0.75,
          newValue: -1.5,
          delta: -0.75,
          reason: "角膜地形图提示角膜散光较初配增加 0.75D，交叉圆柱镜精调后确认。",
        },
      ],
      note: "建议排查揉眼习惯，半年后复查角膜曲率。",
    },
  ];
}
